const initialState: any = {
    user: {
        data: {},
        loading: true,
        loadingState: true,
    },
    generalSettings: {
        data: {},
        loading: true,
        loadingState: true,
    },
    aboutUsOverview: {
        items: [],
        loading: true,
        loadingState: true,
        totalItems: 0,
        totalPages: 0,
    },
    aboutUsOurVision: {
        items: [],
        loading: true,
        loadingState: true,
        totalItems: 0,
        totalPages: 0,
    },
    aboutUsMessageFromChairperson: {
        items: [],
        loading: true,
        loadingState: true,
        totalItems: 0,
        totalPages: 0,
    },
    categories: {
        data: [],
        loading: true,
        loadingState: true,
    },
    serviceCategories: {
        data: [],
        loading: true,
        loadingState: true,
    },
    products: {
        items: [],
        loading: true,
        loadingState: true,
        totalItems: 0,
        totalPages: 0,
    },
    banners: {
        data: [],
        loading: true,
        loadingState: true,
    },
    services: {
        items: [],
        loading: true,
        loadingState: true,
        totalItems: 0,
        totalPages: 0,
    },
    homeFAQs: {
        data: [],
        loading: true,
        loadingState: true,
    },
    productFAQs: {
        data: [],
        loading: true,
        loadingState: true,
    },
    contactFAQs: {
        data: [],
        loading: true,
        loadingState: true,
    },
    themes: {
        items: [],
        loading: true,
        loadingState: true,
        totalItems: 0,
        totalPages: 0,
    },
    gallery: {
        items: [],
        loading: true,
        loadingState: true,
        totalItems: 0,
        totalPages: 0,
    },
    videos: {
        data: [],
        loading: true,
        loadingState: true,
    },
    applications: {
        items: [],
        loading: true,
        loadingState: true,
        totalItems: 0,
        totalPages: 0,
    },
    dashboard: {
        data: {},
        loading: true,
        loadingState: true,
    },
    notices: {
        items: [],
        loading: true,
        loadingState: true,
        totalItems: 0,
        totalPages: 0,
    },
    inquiries: {
        items: [],
        loading: true,
        loadingState: true,
        totalItems: 0,
        totalPages: 0,
    },
    settings: {
        data: [],
        loading: true,
        loadingState: true,
    },
    portfolioType: {
        data: [],
        loading: true,
        loadingState: true,
    },
    popup: {
        items: [],
        loading: true,
        loadingState: true,
        totalItems: 0,
        totalPages: 0,
    },
    portfolio: {
        items: [],
        loading: true,
        loadingState: true,
        totalItems: 0,
        totalPages: 0,
    },
    team: {
        items: [],
        loading: true,
        loadingState: true,
        totalItems: 0,
        totalPages: 0,
    },
    directors: {
        items: [],
        loading: true,
        loadingState: true,
        totalItems: 0,
        totalPages: 0,
    },
    shareUploadedFiles: {
        data: [],
        loading: true,
        loadingState: true,
    },
    contacts: {
        items: [],
        loading: true,
        loadingState: true,
        totalItems: 0,
        totalPages: 0,
    },
    // SEO states matching the `pages` array
    homeSeo: {
        data: {},
        loading: true,
        loadingState: true,
    },
    overviewSeo: {
        data: {},
        loading: true,
        loadingState: true,
    },
    messageFromChairmanSeo: {
        data: {},
        loading: true,
        loadingState: true,
    },
    organizationHistorySeo: {
        data: {},
        loading: true,
        loadingState: true,
    },
    importedProductsSeo: {
        data: {},
        loading: true,
        loadingState: true,
    },
    manufacturedProductsSeo: {
        data: {},
        loading: true,
        loadingState: true,
    },
    noticeSeo: {
        data: {},
        loading: true,
        loadingState: true,
    },
    productionDepartmentSeo: {
        data: {},
        loading: true,
        loadingState: true,
    },
    qualityAssuranceSeo: {
        data: {},
        loading: true,
        loadingState: true,
    },
    qualityControlSeo: {
        data: {},
        loading: true,
        loadingState: true,
    },
    storeAndLogisticsSeo: {
        data: {},
        loading: true,
        loadingState: true,
    },
    gallerySeo: {
        data: {},
        loading: true,
        loadingState: true,
    },
    contactSeo: {
        data: {},
        loading: true,
        loadingState: true,
    },
};

export default initialState;
